name: 8.0-cli-alpine

on:
  push:
    branches:
      - master
      #- feat/add-gha

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          TAGS="${GITHUB_REPOSITORY}:${GITHUB_WORKFLOW}"
          if [[ $GITHUB_WORKFLOW == 8\.1* ]]; then
            TAGS="${GITHUB_REPOSITORY}:${GITHUB_WORKFLOW},${GITHUB_REPOSITORY}:latest"
          fi

          # Set output parameters.
          echo ::set-output name=tags::${TAGS}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./8.0/alpine/cli
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.tags }}

