name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      phpver:
        description: 'Version de php'
        type: choice
        required: true
        options:
          - '8.1'
          - '8.0'
          - '7.4'
          - '7.3'
          - '7.2'
          - '7.1'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        execenv: [ cli, fpm ]
        os: [ alpine ]
        include:
          - execenv: cli
            os: alpine
            tag_latest_on: 8.1  # This value is add only when we are in job cli-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        id: prep
        run: |
          TAGS="${GITHUB_REPOSITORY}:${{ github.event.inputs.phpver }}-${{ matrix.execenv }}-${{ matrix.os }}"
          if [[ "${{ github.event.inputs.phpver }}" == "${{ matrix.tag_latest_on }}" ]]; then
            TAGS="${TAGS},${GITHUB_REPOSITORY}:latest"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./${{ github.event.inputs.phpver }}/${{ matrix.os }}/${{ matrix.execenv }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.tags }}
