name: docker-build

on:
  push:
    branches:
      - master
      - feat/gha-matrix

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        phpversion: [ 8.0, 8.1 ]
        execenv: [ cli, fpm ]
        os: [ alpine ]
        include:
          - phpversion: 8.1
          - execenv: cli
          - os: alpine
            latest: true

    steps:
      - name: Echo details
        run: echo ${{ matrix.phpversion }} - ${{ matrix.execenv }} - ${{ matrix.os }} - ${{ matrix.latest }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          TAGS="${GITHUB_REPOSITORY}:${{ matrix.phpversion }}-${{ matrix.execenv }}-${{ matrix.os }}"
          if [[ ${{ matrix.latest }} ]]; then
            TAGS="${TAGS},${GITHUB_REPOSITORY}:latest"
          fi
          echo ${TAGS}
