name: Update Docker Hub Description
on:
  push:
    branches:
      - master
      - feat/gha-matrix
    paths:
      - README.md
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${GITHUB_REPOSITORY}
          short-description: "PHP Dockerfiles with additional libraries (mainly for our needs)"
          readme-filepath: ./README.md